menu:
    Blog: /
    Archive: /archives/
    lydsnm's Life: http://life.lydsnm.top
    Weibo: https://weibo.com/u/2453162147
    GitHub: https://github.com/donglyu
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2015
